name: Run Gradle on PRs
on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        include:
          - distribution: temurin
            java-version: 21
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Execute Gradle build
        run: ./gradlew marathonDebugAndroidTest 
    continue-on-error: true
